export ZSH="$HOME/.oh-my-zsh" # Oh-my-zsh installation path
ZSH_THEME="af-magic-custom" # Zsh theme
zstyle ':omz:update' mode auto # Update omz automatically without asking
zstyle ':omz:update' frequency 14 # How often to update omz

# Configuration
CASE_SENSITIVE="false" # Case-sensitive completion
HYPHEN_INSENSITIVE="true" # Hyphen-sensitive completion
DISABLE_MAGIC_FUNCTIONS="false" # Disable if pasting URLS and other text is messed up
DISABLE_LS_COLORS="false" # Disable to remove ls colors
DISABLE_AUTO_TITLE="false" # Disable auto-setting terminal title
ENABLE_CORRECTION="false" # Enable command auto-correction
COMPLETION_WAITING_DOTS="false" # Display red dots while waiting for command completion
DISABLE_UNTRACKED_FILES_DIRTY="false" # Disable marking untracked VCS files as dirty
HIST_STAMPS="mm/dd/yyyy" # History command time stamp format

# ZSH Plugins ($ZSH|$ZSH_CUSTOM)/plugins/
plugins=(
  git
  zsh-autosuggestions
)

# Source Configurations
source $ZSH/oh-my-zsh.sh
source $HOME/.zprofile
